### ISSUE TITLE
Display captcha when registering new account

### ISSUE THREAD

**Issue by pitchum** [tigase/siskin-im#10]
Some XMPP servers require solving a captcha before creating a new account.

The captcha is not shown in Siskin, instead the user sees a fallback message containing a URL where the captcha is visible:

> If you don't see the CAPTCHA image here, visit the the web page.
> CAPTCHA web page : https://xmpp.provider.net/captcha/xxxxx.png

The user has to copy-paste the URL in a web browser ant then come back to Siskin to finish the registration. Such process is very crippling. Please make it possible to view the captcha directly in Siskin.

Some hints:
- how to activate [captcha in ejabberd](https://docs.ejabberd.im/admin/configuration/#captcha )
- how to activate [captcha in prosody](https://modules.prosody.im/mod_captcha_registration.html )
- [XEP-0158](https://xmpp.org/extensions/xep-0158.html#register )

**Comment by pitchum** [comment]
Hi there, any news about this?

Today someone told me that it was impossible to create an account on chapril.org because the captcha URL showed a 404 error. I'm pretty sure this is because that person did something wrong when copy-pasting the link into safari.
But anyway, it was enough to make her give up :(

Would it be helpful if I provide a ready-to-use test server?

**Comment by hantu85** [comment]
Currently, we are not working on that as we are working on adding support for MIX and better support for VoIP.
Due to the lack of time, support for CAPTCHA (which still can be used, even without support in Siskin), is still waiting to be added.

If you could prepare ready-to-use test server, which we could use for development and testing, that would be very helpful and I would prioritize this task.

**Comment by pitchum** [comment]
You can use chapril.org as a test server, even though it's already in production ;)
Just let me know the fake accounts you create so that I can delete them if needed.

**Comment by hantu85** [comment]
I was able to implement CAPTCHA support in SiskinIM and BeagleIM and test them against chapril.org. (I've removed test accounts from the server, so there is nothing to clean up).

Those changes will be part of beta builds which should be available soon (ie. via TestFlight) and then will be part of the next release.
