### ISSUE TITLE
GPLv3 is incompatible with the Apple App store Terms of Service.

### ISSUE THREAD

**Issue by Zambito1** [tigase/siskin-im#103]
I noticed this application is distributed under the GPLv3, which has been [known to be incompatible with the Apple App Store Terms of Service](https://www.fsf.org/blogs/licensing/more-about-the-app-store-gpl-enforcement)

Is the app being distributed on the App Store under a separate license?

IANAL, just a concerned citizen.

**Comment by arturhefczyc** [comment]
I am not an attorney or any kind of IP rights specialist. So I may be wrong. However, I am representative of Tigase which is entity distributing and providing our software under AGPLv3 license. So, here is my (ours) understanding.

I do not really see much problem here. 

Mentioned restrictions on a number of devices the app can be installed does not really apply here, as we offer our apps for free on AppStore. And the restrictions, as I understand, apply to paid apps.

And the rest, really is not a problem from my point of view. We provide our apps to use for free. We also provide source code for our apps (and other our AGPLv3 software) for free with public access on GitHub. We allow unrestricted use, copy and modifications to our software within compliance with AGPLv3. Which is basically the general idea of GPL license and the spirit of the free software, as I understand it.

The AppStore is just a medium for us to distribute binary form, usable form of our software. That's it. If you have further questions, or have some comments, please fee free to reopen the ticket.
