### ISSUE TITLE
Support iOS font size general setting (which have no effect on Siskin)

### ISSUE THREAD

**Issue by frenetiks** [tigase/siskin-im#107]
**Is your feature request related to a problem? Please describe.**
People who have Presbyopia usually use the font size general parameter of iOS which can change size of font. But it seems that Siskin don't respect this settings and font are very small for Presbyopia people.
I'm not a iOS specialist but here is an example for settings font size in ios : https://www.youtube.com/watch?v=tIk7PjpETw4

**Describe the solution you'd like**
Siskin should respect the font size parameter.

**Describe alternatives you've considered**
Unfortunately people who have this problem can't use the application. It seems that Whatsapp and other chat app respect this settings, chat discussion can display with big font.

**Comment by hantu85** [comment]
We do not provide a way to change the font size. It may be added in some future version.

**Comment by hantu85** [comment]
Version 7.0-b4 which is available for testing in TestFlight now supports font scaling - it follows iOS settings.

**Comment by hantu85** [comment]
Version 7.0 was released.
