### ISSUE TITLE
Notification Extension Services Problem

### ISSUE THREAD

**Issue by mrpower55** [tigase/siskin-im#108]
Hello There,

I have working on siskin-im and i have facing problem on notification service extension it is didn't execute at all, it is like it is not found on project

Also i try to remove it at all and add new service extension from scratch but also nothing changed

Go be sure i am installing it right i build spectated application and i added it successfully

So please can you telling me if there is any configuration on project that disable notification extensions?

Waiting to here from you guys

Thanks

**Comment by hantu85** [comment]
Notifications extension to work requires APNS certificate to work and XMPP component sending push notifications from XMPP server to your client.

SiskinIM is a client for which there is an existing push notifications component for the XMPP network, but it will only work with SiskinIM builds signed by us as Apple requires that push component notifications must be authenticated by APNS certificate matching certificate used to sign build of the application which should receive notifications.

**Comment by mrpower55** [comment]
> Notifications extension to work requires APNS certificate to work and XMPP component sending push notifications from XMPP server to your client.
> 
> SiskinIM is a client for which there is an existing push notifications component for the XMPP network, but it will only work with SiskinIM builds signed by us as Apple requires that push component notifications must be authenticated by APNS certificate matching certificate used to sign build of the application which should receive notifications.

as i mention i implement everything and it is working fine but i want to working on notification extension service to catch the notification data when it received to the devices 

for more information i want didReceive function on UNNotificationServiceExtension to working smoothly

hope find help to fix that

**Comment by hantu85** [comment]
Working example of UNNotificationServiceExtension is part of SiskinIM. Please be aware that if application is still running in the background on iOS, notification service extension may/will not be called, and notification will be delivered to the method responsible for handling notifications in the AppDelegate.

**Comment by mrpower55** [comment]
> Working example of UNNotificationServiceExtension is part of SiskinIM. Please be aware that if application is still running in the background on iOS, notification service extension may/will not be called, and notification will be delivered to the method responsible for handling notifications in the AppDelegate.

for sure i working on it using background mode but it is still not working :(

any help to fix that, i want to ask if there is any configuration that disable the extenstion?

thanks for your replays

**Comment by hantu85** [comment]
In code or in project settings of SiskinIM there is no flag or configuration option to disable this extension.

**Comment by mrpower55** [comment]
fixed
