### ISSUE TITLE
Notification Extenstion

### ISSUE THREAD

**Issue by mrpower55** [tigase/siskin-im#113]
Hello,

I have using siskin-im and i found i bug on Notification Extenstion it is not working at all

i think at first i have implement it on wrong way but i try to do it on seperated project it is working fine but on siskin-im it is not so please can you help me to fix that?

thanks

**Comment by hantu85** [comment]
Have you confirmed that your push notifications component is sending push notifications to APNS and that it doesn't receive an error as the response?

Have you checked that push notifications component is sending notifications to APNS authenticated with proper SSL certificate?
