### ISSUE TITLE
Conversation Screen Loading data

### ISSUE THREAD

**Issue by mrpower55** [tigase/siskin-im#114]
I have to fix the transform problem on conversation page i disable it by making (inverted = false), but i see the items of conversation is sorted up side down

so i searched a a lot where items array it is receive the information from server and then display the data on screen

all i need to reverse the array before display the data, so please can you help me to get it?

thanks

**Comment by mrpower55** [comment]
any help here?

**Comment by hantu85** [comment]
You need to look at https://github.com/tigase/siskin-im/blob/master/SiskinIM/chat/ChatViewDataSource.swift and adjust it as it holds the structure with loaded messages and is responsible from converting position/row number into message object.

**Comment by mrpower55** [comment]
thank you so much i found what i want

**Comment by kamalkumar13** [comment]
@mrpower55 how did you solve this? can you share your ChatViewDataSource.swift class?
