### ISSUE TITLE
OMEMO encrypted file transfer

### ISSUE THREAD

**Issue by ericschdt** [tigase/siskin-im#12]
As far as I know Siskin does not support OMEMO file transfer like Conversations or other clients do, which would be very convenient to have.

Unfortunately there's no official XEP for OMEMO encrypted file transfer (*), but you can guide yourself at the suggested protocol extension. 

Looking forward to having this gap closed. :)

(*) https://xmpp.org/extensions/inbox/omemo-media-sharing.html

**Comment by woj-tek** [comment]
We are aware of it and already commented on the topic here: #4.

However - are are working on bringing encrypted file transfer to SiskinIM (and BeagleIM as well) so keep an eye on new versions :-)

**Comment by hantu85** [comment]
I'm closing this issue as an encrypted file transfer is now available in SiskinIM and BeagleIM.
