### ISSUE TITLE
Can't delete account if PUSH NOTIFICATIONS is enabled and account is deleted on server

### ISSUE THREAD

**Issue by atol71** [tigase/siskin-im#123]
If an old account that has been deleted from XMPP server has push notifications enabled it is impossible to delete account.

**To Reproduce**
1. Activate push notifications
2. Delete account in server
2. try to delete account in app

**Expected behavior**
Possibility to disable push notifications and delete account.

**Details (please complete the following information):**
 - Siskin Version: 6.4
 - iOS version 14.6
 - iPhone model iPhone 8

**Comment by hantu85** [comment]
Duplicate of #119
