### ISSUE TITLE
the application gives an error in sending messages

### ISSUE THREAD

**Issue by Olik2** [tigase/siskin-im#124]
the application Siskin IM gives an error in sending messages: Your contact offline message queue is full. The message has been discarded. What to do next?

**Comment by hantu85** [comment]
That is not application giving an error, but your contacts server sending you a message with information that your contact inbox is full and this message will not be stored, so it will not receive it.

I think that the only thing you could do is to contact (in some other way) your contact and inform them that his inbox is full or just wait until your contact became online and cleans up the inbox.

**Comment by Olik2** [comment]
The app was downloaded just yesterday. Is it somehow related to mail or messages on the phone?

**Comment by hantu85** [comment]
The issue is with your contact account on their server, not with the app.

**Comment by Olik2** [comment]
how can this problem be solved?

**Comment by Olik2** [comment]
more encryption problems: I sent you an OMEMO encrypted message but your client doesn't seem to support that

**Comment by licaon-kter** [comment]
@Olik2 can you join the support channel so you can get faster responses?

xmpp:tigase@muc.tigase.org?join
