### ISSUE TITLE
Any chance of a beta TestFlight?

### ISSUE THREAD

**Issue by jtmaston** [tigase/siskin-im#126]
**I have a problem with…**
I've switched to XMPP as a daily driver and siskin seems to be one of the best for iOS. I use BeagleIM on desktop ( the beta ) as the stable release didn't have ask the features I needed ( groups didn't support encryption, photo upload didn't work ). I was wondering if a beta was available for siskin too ( I can't seem to get it to build from the xcodeproj ). Thanks!

**Comment by izanp** [comment]
Also interested.
Would really like to test and give feedback.
There is definitely some instability in attaching and sharing files. Also with making / receiving calls.
Some word of late delivery/notifications.

**Comment by licaon-kter** [comment]
The support room said at one point "please send us your icloud email to support@tigase.net", not sure if still the way to get in.

**Comment by jtmaston** [comment]
> The support room said at one point _"please sent a message with your icloud email using form on https://tigase.net/technical-support/ (3rd option) and we can add you to testflight"_, not sure if still the way to get in.  

Well the option doesn't seem to be there anymore... I'd gladly do that if needed

**Comment by licaon-kter** [comment]
Try directly: _"please send us your icloud email to support@tigase.net"_, or well, mail first to ask :)

**Comment by woj-tek** [comment]
You can use this link: https://testflight.apple.com/join/zDSl1D3s to join the TestFlight.

**Comment by jtmaston** [comment]
> You can use this link: https://testflight.apple.com/join/zDSl1D3s to join the TestFlight.

Thank you! I'll mark it as closed.
