### ISSUE TITLE
iPhone SE, iPAD 4 IOS version 14+ Audio Options Do Not stay for User Selection

### ISSUE THREAD

**Issue by usamad** [tigase/siskin-im#128]
Dear Siskin Team/Andrzej,

This issue is to report an application Behavious. Steps to produce/re-produce are below:
- Using iPhone SE 2020, iPhone 8, iPad 4
- perform an Audio Call from Android (Conversation App) to a User on IOS (Using Siskin IM)
- The Use Can Click to Pick-Up the Call (Blue Buton)
- However the Call Options Screen with Options for Speaker Phone or Ear-Piece (Device) appears Momentarily
- Call Work but with Speaker Phone Mode on IOS Device. No way to Switch to Ear-Piece.
- By Putting Phone to ear Also Does not swich the call to Ear-Piece, May be the Proximity Sensor or any other support is not working or broken. 

Thanks.

**Comment by hantu85** [comment]
This issue is related to the issue #56 and knowing cause of that issue I can say it is a duplicate.
