### ISSUE TITLE
Proper support of OMEMO group chats

### ISSUE THREAD

**Issue by ericschdt** [tigase/siskin-im#13]
As far as I know, Siskin does not yet support OMEMO group chats properly. That is however important in order to undoubtedly recommend it in the future to the general apple friend.

**Comment by woj-tek** [comment]
It's on our roadmap :-)

**Comment by wiktor-k** [comment]
Glad to hear that Wojtek! I did recently play with Siskin on my friend's phone and it looks very nice. Just a few minor issues (like this one) and it'll be perfect! :)

**Comment by mdosch** [comment]
@woj-tek 
Is this roadmap available somewhere? I didn't see any milestone linked to this issue and am curious if this might be supported with version 6.0 coming (hopefully) soon. 😃

**Comment by hantu85** [comment]
It will come at some point but as it was stated there is no exact ETA and it is not part of version 6.0.

**Comment by woj-tek** [comment]
It's implemented and available since 6.2.
