### ISSUE TITLE
Hello , when i try to run the clone project i found openssl and webrtc frameworks missing .Can anyone let me know how to resolve those missing frameworks.

### ISSUE THREAD

**Issue by RamChandaluri777** [tigase/siskin-im#130]
**Describe the bug**

**To Reproduce**
2. Open '....'
3. Do '....'

**Expected behavior**

**Screenshots**

**Details (please complete the following information):**
 - Siskin Version: [e.g. 6.0.0]
 - Branch: [e.g. master]
 - Xcode version: [e.g. 11]
 - iOS version [e.g. 11.0]
 - iPhone model [e.g. iPhone 11]

**Additional context**

**Comment by woj-tek** [comment]
Please check this:
* https://github.com/tigase/openssl-swiftpm
* https://github.com/tigase/webrtc-swiftpm

**Comment by hantu85** [comment]
Or just run `update-frameworks.sh` script from the root directory.

**Comment by RamChandaluri777** [comment]
Thanks @hantu85  ,it worked well.But i found again tigaseSwiftOmemo.framework missing.could you  pls help me with that.

**Comment by RamChandaluri777** [comment]
Thanks @hantu85  it worked
