### ISSUE TITLE
Let us add paragraphs to messages

### ISSUE THREAD

**Issue by Reinachan** [tigase/siskin-im#135]
**Is your feature request related to a problem? Please describe.**
It's currently (to my knowledge) not possible to add newlines/paragraphs. This is frustrating when you're writing longer messages as they'll quickly become hard to read.

**Describe the solution you'd like**
Make the return button not act like a send button. There is already a send button on the icon bar above.

**Comment by hantu85** [comment]
Please go to `Settings` then `Chats` and disable `Send message on return`. This should make work as you expected and send button is already there.
