### ISSUE TITLE
Underline markdown persists even when "_" deleted

### ISSUE THREAD

**Issue by jtmaston** [tigase/siskin-im#138]
**Describe the bug**
When "_" is used to underline text, despite deleting the characters, the message still displays as underlined.

**To Reproduce**
1. Open chat with someone
2. Style a message with the beginning _
3. Delete the _
4. Message still displays as underlined.

**Expected behavior**

**Details (please complete the following information):**
 - Siskin Version: Testflight 7.0 (3)
 - iOS version 14.7.1
 - iPhone model iPhone 11

**Additional context**

**Comment by hantu85** [comment]
This issue will be fixed by the next beta build.

**Comment by jtmaston** [comment]
Thanks!
