### ISSUE TITLE
Existing bookmarks don't open/show

### ISSUE THREAD

**Issue by stevenroose** [tigase/siskin-im#14]
So I have an account that is part of some public channels and private group chats. (This translates to MUC bookmarks with autojoin enabled in Conversations and Dino.)

When I login to Siskin, I'm expecting those chats to be visible and joined automatically. Currently
- they are not visible and joined automatically
- there is no way to actually find those chats anywhere.

The only thing I could do was to manually join them by typing in their JIDs.

**Comment by woj-tek** [comment]
@stevenroose would it be possible to share name of the server (domain + ideally server software used)?

**Comment by jnaeff** [comment]
Hi ! 

I have the same issue. I talked to our XMPP expert internally. He told that we support the old and new format of XMPP bookmarks (bookmark conversation). We run ejabberd 19.05.

Jeroen

**Comment by hantu85** [comment]
This issue should be fixed in the next release by a workaround for weird behavior of PEP implementation in ejabberd https://github.com/tigase/tigase-swift/commit/6111e5b262207983f47303cd09543045e416920f
