### ISSUE TITLE
7.0 beta 4 breaks image upload from gallery

### ISSUE THREAD

**Issue by jtmaston** [tigase/siskin-im#140]
**Describe the bug**
Cannot upload images from the gallery, it fails with message "it was not possible to access this file". Sending images from camera ( I.e. taking photos works fine)

File upload tested working in beta 3
Working neither in MUC nor in private chat.
Settings associated to media upload set to allow it.
Permissions set to access all images ( previews are shown properly ).

**To Reproduce**
* Press the picture icon to attach an image from gallery
* Fail

**Expected behavior**
An image should be sent.

**Details (please complete the following information):**
 - Siskin Version: 7.0 beta 4
 - iOS version 14.8
 - iPhone model iPhone 11

**Comment by hantu85** [comment]
This only happens if `original` media quality is selected for sharing photos.

**Comment by hantu85** [comment]
This issue will be fixed in the next beta build.
