### ISSUE TITLE
Group search not working properly with my server!

### ISSUE THREAD

**Issue by hashilsemin** [tigase/siskin-im#141]
Somehow search in the join group option doesn't show every group.
Could it be the issue of my xmpp server?

**Comment by woj-tek** [comment]
What server software do you use? Could you expand on "doesn't show every group"? Does it mean no results or simply some rooms missing?

**Comment by hashilsemin** [comment]
> What server software do you use? Could you expand on "doesn't show every group"? Does it mean no results or simply some rooms missing
I have around 250 groups (public), but in the search initially, it only shows 77 groups and couldn't them search by words too.

**Comment by hantu85** [comment]
Closing due to incomplete bug report and no answers for asked questions.
