### ISSUE TITLE
Support quote rendering

### ISSUE THREAD

**Issue by wurstsalat3000** [tigase/siskin-im#148]
Messages starting with a `>` should be rendered differently, so that they contrast themselves from regular messages.

This is a feature of both XEP-0393 (I've seen the discussion in #104) and Markdown.

I imagine something like Github does for quoting:

---------------

> This is a quote

And this is a message referring to a quote

---------------

**Comment by hantu85** [comment]
@wurstsalat3000 This feature is already available as part of the version released in TestFlight.

**Comment by wurstsalat3000** [comment]
That's great news, thank you!
