### ISSUE TITLE
Automatic image compression

### ISSUE THREAD

**Issue by wiktor-k** [tigase/siskin-im#15]
**Is your feature request related to a problem? Please describe.**
When I send images from an iPhone (either from gallery or photos) they're very big (~4 MB). It would be nice if they were automatically compressed.

**Describe the solution you'd like**
Compress all images so they're max 500 KiB. This could be configurable in the settings.

**Describe alternatives you've considered**
Manual compression of images, or waiting for super-long upload speeds.

**Additional context**
N/A

**Comment by hantu85** [comment]
Thank you for suggestion. Most likely we will add a similar future, but instead of automatic compression, it would be better (in my opinion) to ask the user for expected file size (or image quality) as in some cases it is very useful or even required to have original files sent.

**Comment by wiktor-k** [comment]
Good idea. I also want original quality images sometimes but for most cases (95%) I don't mind if my cat meme pictures are not in full HD :)

**Comment by hantu85** [comment]
Feature is now part of a beta build released on TestFlight and will be part of upcoming version 6.1
