### ISSUE TITLE
new version 7.0 on iphone messages unencrypted

### ISSUE THREAD

**Issue by onefreeworld** [tigase/siskin-im#154]
Hi there,

my iphone SE2020 iOS 15.1 
got the new app-update to 7.0 (from app-store today)

messages send from siskin now are unencrypted. 
any helpful advise is appreciated how to restore OMEMO encryption.
thank you!

**Comment by licaon-kter** [comment]
Sounds like https://github.com/tigase/beagle-im/issues/86

**Comment by onefreeworld** [comment]
Hi guys, thank you. I don`t understand what to do with this information. I am more kind of a noob ;) could you please explain? thx

**Comment by ValdikSS** [comment]
I can confirm that OMEMO does not enable in new version. All outgoing messages are unencrypted. The incoming OMEMO-encrypted messages are received just fine.

**Comment by onefreeworld** [comment]
Reminds me to add: Messages send from windows gajim on same account are encrypted too

**Comment by licaon-kter** [comment]
As said in the support channel, it might work when you set it specifically, not use "default". 

A fix was already pushed to Test Flight.

**Comment by onefreeworld** [comment]
Where within the settings can I change this? 
I can only choose OMEMO on or none. See picture attached (sorry its huge ;) )

![omemo01](https://user-images.githubusercontent.com/44290360/144497901-1e4e9472-1442-49af-b883-4f5ce4f355fc.PNG)


Cool, thanks for already test flight :)

**Comment by licaon-kter** [comment]
@onefreeworld I think that was the bug, the Setting was not applied, so only per chat specified omemo selection was used. So if you've setup as omemo would be fine, but "default" would be not.

**Comment by onefreeworld** [comment]
Sorry I don't get it. 
The setting was always on OMEMO and I had no encryption after the update anymore.
So I double checked and turned it to none, tried it and turned it back to OMEMO. Still does not work.

**Comment by licaon-kter** [comment]
There are two places, right? 

In app Settings, Default OMEMO/No
And in an **actual chat**, settings

You have both on OMEMO and it still broken?

**Comment by onefreeworld** [comment]
Your're kidding? :D :D :D I had to go to each single contact to turn omemo on in each chat settings. lol. You've no idea how many times I looked there and didn't realize it was green but on default. Nicely hidden ;)
Still waiting on confirmation from recipients, but in my own gajim I am "green" again. 
Thank you so much for all your patience! <3
