### ISSUE TITLE
Push notifications are broken again 😡

### ISSUE THREAD

**Issue by milkywade** [tigase/siskin-im#159]
**Describe the bug**
Again, push notifications only work when app is in foreground.

i tried disabling and re-enabling push notifications but after disabling I’m unable to enable again (everything is ok in settings)

using ios15.2 and iPhone 11.

![4524C309-ADAD-4F94-A595-51A70294B3AB](https://user-images.githubusercontent.com/43685172/147811362-d185e2fa-6fdb-4122-aa72-7300d4398228.jpeg)

**Comment by hantu85** [comment]
TestFlight build with a fix for this issue was released yesterday. 

The current version available at the AppStore was being tested for a long time and no one reported this issue before.

**Comment by milkywade** [comment]
I must say that push notifications worked for a while… until they did not

--
