### ISSUE TITLE
Cant upload images from gallery or other one

### ISSUE THREAD

**Issue by centertivevier** [tigase/siskin-im#171]
Describe the bug
Cannot upload images from the gallery or other one, it fails with message "Could Not Retrieve filed size ". Currently yesterday was all fine.

Reboot of the phone was not solved the problem. With Conversations/Dino are all fine.

To Reproduce

    Press the picture icon to attach an image from gallery
    Fail

Details (please complete the following information):

Siskin Version: 7.0.1
    iOS version: 14.4
  Server: Ejabberd 21.12

**Comment by hantu85** [comment]
Are you sure that you are sharing image and not video? We are aware of this issue for videos, and it is solved in upcoming version. 

For images, that could also mean that iOS was not able to fetch this image from the iCloud if sync was enabled.
