### ISSUE TITLE
describe how to implement OMEMO Encryption

### ISSUE THREAD

**Issue by majdalden** [tigase/siskin-im#175]
Is there any description of how OMEMO encryption is implemented step-by-step Siskin?

**Comment by hantu85** [comment]
OMEMO implementation in SiskinIM is based on XMPP OMEMO specification which can be found https://xmpp.org/extensions/xep-0384.html in version 0.3.0. The actual OMEMO library used by SiskinIM can be found here https://github.com/tigase/tigase-swift-omemo/

**Comment by Neustradamus** [comment]
@tigase team, I think it can be closed :)
