### ISSUE TITLE
Website's Documentation link is blocklisted, community link is down

### ISSUE THREAD

**Issue by ABelliqueux** [tigase/siskin-im#179]
On the website's menu, the documentation link is linking to a website ~~that's down~~ that's on [a blocklist](https://github.com/notracking/hosts-blocklists): 

https://docs.tigase.net/tigase-ios/master-snapshot/Tigase_Swift_Guide/html/

The 'community' link at the bottom of the page is also dead : 

https://tigase.tech/projects/tigase-ios-messenger

EDIT: for whatever reason, `tigase.net` is on a host blocklist that's used for adblocking :

https://github.com/notracking/hosts-blocklists/blob/master/domains.txt

I suspect it's the same for `tigase.tech`, although I did not find any occurence in the blocklists yet.

I reported a false positive on the list's project repo : https://github.com/notracking/hosts-blocklists/issues/747

**Comment by woj-tek** [comment]
Thank you for tracking root cause and reporting it.

> The 'community' link at the bottom of the page is also dead :

Could you point exact location? I checked the page and sources and there is no mention of either `tigase.tech` or `tigase-ios-messenger`

**Comment by ABelliqueux** [comment]
Ok so I did a  few tests and wrote a lot of stuff that I'm leaving under here for the record, but I should have started with the obvious test : 

https://downforeveryoneorjustme.com/tigase.tech

shows tigase.tech is down. So this one may not be related to any blocking.

### Old Message (probably irrelevant now) : 

I assumed it was in there, but I'm not sure anymore... I still can't access `tigase.tech`, although `dig` shows some records : 

```bash

$  curl tigase.tech
curl: (6) Could not resolve host: tigase.tech

$ ping tigase.tech
ping: tigase.tech: No address associated with hostname

$ dig tigase.tech @8.8.8.8

; <<>> DiG 9.16.22-Debian <<>> tigase.tech @8.8.8.8
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 28536
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;tigase.tech.			IN	A

;; AUTHORITY SECTION:
tigase.tech.		900	IN	SOA	ns-1478.awsdns-56.org. awsdns-hostmaster.amazon.com. 1 7200 900 1209600 86400

;; Query time: 59 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Wed Mar 09 12:04:57 CET 2022
;; MSG SIZE  rcvd: 125

```

I can access other *.tech sites (e.g : https://get.tech/ ) , so I'm ruling out *.tech blocking in my DNS setup.
I tried with several different public IP/providers, various DNS and devices, and still no access to `tigase.tech`.

**Comment by woj-tek** [comment]
'tigase.tech' is old domain, I changed the community link to point to github

**Comment by ABelliqueux** [comment]
Great, this settles that then. 
Feel free to close the issue as there's not much more that can be done on your side for de-listing `tigase.net` I guess.
Thanks for your time and answers !
