### ISSUE TITLE
SiskinIM crashes when private chat of MUC is in contact list

### ISSUE THREAD

**Issue by ingoj** [tigase/siskin-im#18]
**Describe the bug**
When you receive a private message from within a MUC a new chat with the address of the MUC is created, e.g. ejabberd-de@conference.conversations.im. 
Trying to join that MUC is crashing SiskinIM. 

**To Reproduce**
- have a private message from a MUC you haven't currently joined in SiskinIM, e.g. by asking someone to send you a private message in that MUC. 
- this should open a new chat in Siskin with address of the MUC
- now try to join the MUC by tapping on the "+" and "Join group chat" and enter the appropriate settings. 
- when tapping on Join, Siskin crashes. 

**Expected behavior**
Well, not crashing of course... ;-) 
Maybe check against addresses of existing chats and act accordingly...

**Comment by hantu85** [comment]
Fix was applied and a new build was released for internal testing and should be soon available in TestFlight.

**Comment by hantu85** [comment]
This issue should be fixed in the recent build.
