### ISSUE TITLE
Omemo Encryption

### ISSUE THREAD

**Issue by mrpower55** [tigase/siskin-im#180]
Hello,

I want to ask how we can enable Omemo Encryption for both one to one conversation and also group messaging

We want Omemo encryption to be automatic selected for all

I have searched a lot on code but can't get the right way to do that

Please help me on that

Thanks

**Comment by licaon-kter** [comment]
`Settings -> Chats -> Message Encryption: OMEMO (was: None)` should do just that.

Do note that in group encryption might be broken in current version 7.1 but possibly fixed in soon to be released 7.2.

**Comment by mrpower55** [comment]
thank

> `Settings -> Chats -> Message Encryption: OMEMO (was: None)` should do just that.
> 
> Do note that in group encryption might be broken in current version 7.1 but possibly fixed in soon to be released 7.2.

Thank you for your quick answer, yes i see it, i want it to be automatic selected the OMEMO so i should changed the default value for it?

**Comment by licaon-kter** [comment]
> i want it to be automatic selected the OMEMO so i should changed the default value for it?

Dunno exactly, but https://github.com/snikket-im/snikket-ios is a fork that has that Enabled by default iirc

**Comment by hantu85** [comment]
@mrpower55 If you enabled `Settings -> Chats -> Message Encryption: OMEMO` then all newly created or joined conversations will be encrypted by default.

**Comment by mrpower55** [comment]
> @mrpower55 If you enabled `Settings -> Chats -> Message Encryption: OMEMO` then all newly created or joined conversations will be encrypted by default.

i have try it and it is working fine for one to one conversation, but on groups when try to send message it is showing me this error
(this room is not capable of sending encrypted messages, please change encryption settings to be able to send messages)

this is only for muc groups messages, so shall i make some changes for muc?

**Comment by hantu85** [comment]
No, that error means that the room to which you want to send an encrypted message is not "members-only" and/or does not broadcast other user's real jids to you. In this case, usage of OMEMO is not possible.

**Comment by licaon-kter** [comment]
There is a difference between a "public channel" = no encryption and a "private group" = encryption possible.

 A private group is "members only" and "jid/address is visible to everyone".

How did you create the MUC/room/group?

**Comment by mrpower55** [comment]
> No, that error means that the room to which you want to send an encrypted message is not "members-only" and/or does not broadcast other user's real jids to you. In this case, usage of OMEMO is not possible.

oh i see, so only (memebers-only) groups able to use omemo encryption?

**Comment by mrpower55** [comment]
> There is a difference between a "public channel" = no encryption and a "private group" = encryption possible.
> 
> A private group is "members only" and "jid/address is visible to everyone".
> 
> How did you create the MUC/room/group?

i guess i am create it using public channel so the omemo is can't work on it right?

**Comment by licaon-kter** [comment]
Nope, you can convert it to a private one from a client that allows you to do that like Gajim or Dino

**Comment by licaon-kter** [comment]
> can i convert public group to private group?

Yes, login as the owner with Gajim or Dino, and see group settings

**Comment by mrpower55** [comment]
thank you very much for your help guys
