### ISSUE TITLE
Supported XEP List?, SRTP Info

### ISSUE THREAD

**Issue by kannasakamoto** [tigase/siskin-im#181]
Where can I find a list or documentation of the XEP's that Siskin.im supports?

Does Siskin support E2EE for voice/video calls?
Or is the "XEP-0320: Use of DTLS-SRTP in Jingle Sessions" needed?
Or is this XEP being implemented?
"Verify encrypted A/V calls with OMEMO" https://gist.github.com/iNPUTmice/aa4fc0aeea6ce5fb0e0fe04baca842cd
Does Siskin support ZRTP or SRTP?

I also do not see much clear documentation of which XEP's are implemented on servers that relate to a/v calls. A resource on this would be amazing.

**Comment by hantu85** [comment]
List of implemented and used XEPs https://github.com/tigase/siskin-im/blob/master/siskin-im.doap
