### ISSUE TITLE
Server iqs

### ISSUE THREAD

**Issue by mrpower55** [tigase/siskin-im#189]
Hello,

i want to ask where i can debug all IQs that received from server?

i want to debug all of it before it is going to message event handler, presene event hander, and so on

so please can you help me to figure that?

thanks

**Comment by hantu85** [comment]
If you want to hook up at a low level, you could try to use `XmppStanzaFilter` for that.

**Comment by mrpower55** [comment]
Than you for your answer, can you telling me more about XmppStanzaFilter ?

is it implemented on siskin or shall i do?

**Comment by hantu85** [comment]
It is part of TigaseSwift library which is used by Siskin IM. This is a protocol, so you will need to implement it and register in `XmppModulesManager`.

**Comment by mrpower55** [comment]
Hello,

i have try a lot to do that, i have created a class that implement the protocol XmppStanzaFilter and then try to register it as module but it is not working.

also i try to implement the protocol using XmppService but also it is not

i have searched a lot how i can implement it but as you know XMPP community is poor

so please if you can help me to know the correct way i can implement it as use it to trace all Stanzas that income and outcome from app

hope i can find your help soon

thanks

**Comment by mrpower55** [comment]
After many try i finally implement it and it is working fine now i can trace all stanzas that income and outcome

thank you so much for your help
