### ISSUE TITLE
No such module 'TigaseSwift' n Framework Errors

### ISSUE THREAD

**Issue by pasha4uu** [tigase/siskin-im#19]
Hello 
when i run clone Project from GitHub Im getting this type of errors 
No such module 'TigaseSwift' 
No such module 'TigaseSwiftOMEMO' 
No such module 'openssl'

that frameworks not contains in the project n it showing not properly like disable 

please suggest and any help would be more appreciated ....

**Comment by hantu85** [comment]
TigaseSwift, TigaseSwiftOMEMO and openssl frameworks are not part of this repository and are manually downloaded and then added to the project in XCode, so downloading only this repository will not allow you to build a project.

TigaseSwift and TigaseSwiftOMEMO are available at https://github.com/tigase/tigase-swift and https://github.com/tigase/tigase-swift-omemo. 

For openssl we are using a custom build of openssl from https://github.com/krzyzanowskim/OpenSSL.

We will be working on moving to SwiftPM as a dependency management tool which will be able to automatically download and resolve issues like that.

**Comment by faraan** [comment]
Hi , 

I tried to add openssl , but every-time it gives same error No such module 'openssl'
Can you please share how we can implement openssl into to the project ?

Thanks

**Comment by hantu85** [comment]
We have a workspace in XCode to which we have added TigaseSwift, TigaseSwiftOMEMO, SiskinIM and openssl project which I've mentioned before (full project, not generated library).
Then we use output of that openssl project in SiskinIM by adding it as an embedded library.
