### ISSUE TITLE
Build Requirements - iOS 12 vs. iOS 13

### ISSUE THREAD

**Issue by MMeldrum** [tigase/siskin-im#193]
**I have a problem with…**
Building Siskin-IM in XCode 13.4.1 / iOS 13.0

**Details:**
I have cloned master and run ./update-frameworks.sh but receive the following error:

`XCode-Projects/siskin-im/SiskinIM - Share/ShareViewController.swift:549:58: 'unarchiveObject(with:)' was deprecated in iOS 12.0: Use +unarchivedObjectOfClass:fromData:error: instead`

I then tried building using iOS 12.0 but the Martin library dependency complains that it requires iOS 13.0.

What am I missing here? Any help very much appreciated.

**Comment by hantu85** [comment]
You have received a warning about the usage of a method that is deprecated. This is not an error - just a warning.

**Comment by MMeldrum** [comment]
So it is. Dear god. 🤦‍♂️ Apologies - it had been a long day! Thanks for the reply.
