### ISSUE TITLE
Long press any message - meaning of clock symbol

### ISSUE THREAD

**Issue by gitbq** [tigase/siskin-im#198]
Hi

I'm trying to prepare some info to assist some real newbies to understand the basic workings of the iOS app. Using it with snikket server.

When I long press any message a menu appears which includes "more" at the bottom. This allows the selection of multiple messages.

At the bottom of the screen there are two icons. Left hand side is a clock icon that can be toggled to filled or clear. The right hand side has the standard iOS share menu.

What does the clock symbol mean and/or do?

Is this screen intended in any way allows me to manually delete multiple messages? ( I have no functionality on this screen.)

Thanks in advance.

**Comment by hantu85** [comment]
No, this screen is intended only to "share" messages (ie. copy them). "clock" button just enables and disables copying time of the message with a message body

**Comment by gitbq** [comment]
Thanks 👍
