### ISSUE TITLE
Certificate Issue

### ISSUE THREAD

**Issue by WhiteFrank73** [tigase/siskin-im#199]
**Describe the bug**
When i open the siskin.im app as alwys since today it appears the msg:
Certifikate Issue
Server for domain tigase.im has an invalid certificate for tigase.im
with fingerprint etc. issued by R3 with fingerprint etc. Do you trust this certificate? I press no because I think it might be compromised.

**To Reproduce**
1. Go to 'settings'
2. Open 'the account'
3. Click on 'activ'

**Expected behavior**
To be active and can write msg`s.

**Screenshots**

**Details (please complete the following information):**
 - Siskin Version: [7.3]
 - iOS version [16.0.2]
 - iPhone model [iPhone 8]

**Additional context**

**Comment by licaon-kter** [comment]
https://crt.sh/?q=tigase.im looks fine

**Comment by hantu85** [comment]
There was an issue with automatic renewal of SSL certificates for `tigase.im` domain. This issue was fixed and certificate was renewed. Now it should work using new and valid SSL certificate.

**Comment by WhiteFrank73** [comment]
Hi,

yes! now its fine again Thank you for support :)
