### ISSUE TITLE
Keyboard overlay blocks input field

### ISSUE THREAD

**Issue by jnaeff** [tigase/siskin-im#2]
Hi!

I must say I really starting to like the client! It is really improving the last couple of versions! Keep up the good work! I found one really enjoying bug. I use an iPhone 5SE. And if I want to input something in can't in the lowest input field. See screencast. 

![My Movie](https://user-images.githubusercontent.com/1419331/63227609-6d30d100-c1e8-11e9-8e1d-39b957dc9ff8.gif)

**Comment by hantu85** [comment]
Thank you for reporting this issue. I've replicated the issue and fixed it, so in the next version (most likely 5.3) it will be fixed.

**Comment by jnaeff** [comment]
Thanks !
