### ISSUE TITLE
Spamming

### ISSUE THREAD

**Issue by amtrakuk** [tigase/siskin-im#204]
I have a problem with spamming from contact requests

There doesn't seem to be a way to block cold-calling contact requests.  My brother is saying he gets push notifications for people wanting to start a chat/add a contact.  There does not seem to be a way to block all except contacts on list.  I have tried by making a new xmpp account and yes I get notifications and uninvited chat requests.  How can I block all notifications/contact requests except contacts I have added?

**Details (please complete the following information):**
 - Tigase version: [e.g. 8.1.0]   SISKIM-IM 7.3
 - JVM flavour and version [e.g. AdoptOpenJDK11]
 - Operating system/distribution/version [e.g. Linux Ubuntu 20.04]  iOS 15.6.1 (iPhone 7)

**Comment by hantu85** [comment]
In Siskin Settings, in Notifications, you have a setting to disable notifications from unknown (people not in your roster/contact list). This should remove no. of contact request notifications and spamming chats.

Also, when you open a chat with someone, by tapping on its name in the top bar, you will see contact settings and there you can select "Block" to block this user.

There is a new version (it is currently being tested) that allows blocking of whole domains (in the reaction of incoming chats/subscription requests).

**Comment by hantu85** [comment]
No, it may happen if your XMPP server would fail to enable this feature on the server side, ie. the feature is not implemented if I recall correctly.

**Comment by amtrakuk** [comment]
Learn something new every day!   Yes there is a spam setting on xmpp.jp

Thanks for the advise!
