### ISSUE TITLE
DOAP links to old logo (404)

### ISSUE THREAD

**Issue by wurstsalat3000** [tigase/siskin-im#207]
Siskin IM's logo changed with f5cb520610e067686aef9ab7e144904d24defa49, and it looks nice :)

However, you forgot to update Siskin IM's DOAP file, which links to the old logo (404). The same goes for Beagle IM.

**Comment by hantu85** [comment]
Siskin with updated logo was not released yet as a stable version, but only as a beta build. When it will be released as a stable version, logo will be updated in DOAP file as well.

**Comment by wurstsalat3000** [comment]
Fixed in f62410d5261bda38516de0470f11e8a49e3282f3
