### ISSUE TITLE
[feature] add option to edit contacts name

### ISSUE THREAD

**Issue by foss-** [tigase/siskin-im#21]
**Is your feature request related to a problem? Please describe.**
While it is possible to set a name for a contact when adding it, vesion 5.7 does not allow editing that name afterwards. This is a problem a) because mistakes happen and there might be an error in the name b) existing contacts may all have their jid instead of their name and no way to adjust that information.

**Describe the solution you'd like**
Why not add a "Name" field to the contact informations screen?

**Comment by hantu85** [comment]
If you long tap on the contact from the list of contacts you have a menu and there is an option to edit contact name, so the feature is there.

**Comment by foss-** [comment]
Awesome, thanks so much. Wasn't expecting it there. Hope I can remember :)
