### ISSUE TITLE
How to open 1-1 private chat with someone not in the roster

### ISSUE THREAD

**Issue by arturhefczyc** [tigase/siskin-im#219]
I have added a new account to the SiskinIM. And this is a fresh installation with no other accounts, no roster entries.

Now I am trying to open a chat with a specific JID.

However, I cannot find an option to send a message to a JID. As you can see on attached screenshot, I can only open a group chat. Is there a way to send a message to a JID?

<img width="795" alt="Screenshot 2023-05-05 at 16 28 36" src="https://user-images.githubusercontent.com/1848738/236584570-9b5a6a2e-9cc9-4dc9-8bc6-3f92897cdbaa.png">

**Comment by woj-tek** [comment]
I think it's not possible to start a chat with JID without adding it to roster (in Siskin), thus going to contact section, adding a contact and then opening the chat seems to be the solution here.

**Comment by arturhefczyc** [comment]
OK, I think this makes sense and is good enough.
