### ISSUE TITLE
My app size continuously increasing for one user it become 50+ GB app

### ISSUE THREAD

**Issue by dhaval-dobariya** [tigase/siskin-im#227]
**App size increasing because of siskinim_main.db-wal file**
On every app launch app size is increasing, after some observation I found that siskinim_main.db-wal file size is increasing and for one of my user it become 50+ GB size file.

**To Reproduce**
1. Do some communications with users 
2. Relaunch the app
3. Observe db-wal file size

**Expected behavior**
I made some search about this issue and I found this file size become zero KB, correct me if I am wrong.

**Screenshots**
Please check this screenshots

| File size | File path | App Screenshot |
|-|-|-|
| ![Screenshot 2023-07-10 at 11 29 57 AM](https://github.com/tigase/siskin-im/assets/51996176/f416a830-e199-4a60-a771-dafbf2c54042) | ![Screenshot 2023-07-10 at 11 22 58 AM](https://github.com/tigase/siskin-im/assets/51996176/42c9232d-0bfe-488c-8b88-028d61253ec3) | ![image](https://github.com/tigase/siskin-im/assets/51996176/f90e704d-b744-4f4a-ae92-f966b8a3c0a8) |

**Details (please complete the following information):**
 - Siskin Version: 6.1
 - Branch: master
 - Xcode version: 14.2
 - iOS version 16.5.1
 - iPhone model iPhone 14 Pro Max

**Comment by licaon-kter** [comment]
Latest version is 7.x, you can reproduce with that too?

**Comment by dhaval-dobariya** [comment]
> Latest version is 7.x, you can reproduce with that too?

Sorry I can't migrate now, is there any fix in latest version related to this issue?

**Comment by licaon-kter** [comment]
You're the first one to report such a thing, who knows?

Is this Siskim from Tigase or some custom version that you build?

**Comment by dhaval-dobariya** [comment]
> You're the first one to report such a thing, who knows?
> 
> Is this Siskin from Tigase or some custom version that you build?

This is pure Siskin from Tigase. Because I have not built any custom feature on it. Only UI is mine, rest database and all operations are as it is since I cloned Tigase repo.

**Comment by hantu85** [comment]
> I made some search about this issue and I found this file size become zero KB, correct me if I am wrong.

WAL files should be "cleaned up" eventually and should be zero (or small). This file is a Write Ahead Log of SQLite3 (database library). We are using SQLite3 library built in the operating system (we do not ship our own version).

Here is a similar topic from SQLite3 library forum - https://sqlite.org/forum/info/54e791a519a225de

I've checked an older version of DB library wrapping SQLite3 that we are using and I think it could contain issue mentioned in this forum at that time, but as I see it is already fixed now.

**Comment by hantu85** [comment]
Please note that this is very old version of the application source code that you are using and we are not maintaining this version any more.

**Comment by dhaval-dobariya** [comment]
> 

I understand that, but if this is database access or migration related issue which may occur if user continuously update new app from AppStore then it may be issue at Tigase side.

And we are not sure if I deliver new update with latest SDK will fix this issue for that user.

If you guys can help about how I can add some block of code to reduce that file size then it will be big help.

**Comment by hantu85** [comment]
As I've mentioned, fix in our database wrapper for SQLite3 already fixes this issue and will resolve WAL file size - on the newest (or most likely just newer) version of Siskin IM, this issue will not take place and will be resolved if it happened already,

**Comment by dhaval-dobariya** [comment]
> As I've mentioned, fix in our database wrapper for SQLite3 already fixes this issue and will resolve WAL file size - on the newest (or most likely just newer) version of Siskin IM, this issue will not take place and will be resolved if it happened already,

Ok let me migrate to latest version.

**Comment by dhaval-dobariya** [comment]
Latest version fixed app size issue, but now facing different issue

Now that user is facing connection time issue, that is able to send message after 2 to 3 minutes. Every time he lauches the app his Tigase connection is taking time.

**Comment by dhaval-dobariya** [comment]
> Latest version fixed app size issue, but now facing different issue
> 
> Now that user is facing connection time issue, that is able to send message after 2 to 3 minutes. Every time he lauches the app his Tigase connection is taking time.

Posted as separate issue, so closing this. https://github.com/tigase/siskin-im/issues/235
