### ISSUE TITLE
Clock icon

### ISSUE THREAD

**Issue by netuser01** [tigase/siskin-im#243]
Hello,

Im using Siskin IM version 7.3.3 on a ipad using 17.5.1 as the OS. 

When using Siskin, I’m going to the messages I send and receive. I hold down the message and click on “More”, there are two options appear. one is a clock on the left side that when I click on it, it becomes solid. When i click again, it is no longer appearing solid.

What is the purpose of the clock icon?

Thanks for your help.

**Comment by hantu85** [comment]
This button enables/disables adding timestamps to copied messages.

**Comment by netuser01** [comment]
Thanks.
