### ISSUE TITLE
SVG version of the Siskin IM logo

### ISSUE THREAD

**Issue by sjehuda** [tigase/siskin-im#246]
Good day!

I would be glad to obtain an SVG version of the Siskin IM logo, in order to include it in the list of recommended XMPP client of FASI (an HTML invite page for XMPP.

See https://git.xmpp-it.net/sch/FASI/issues/1

**Comment by arthef** [comment]
@hantu85 could you please provide requested files?

**Comment by sjehuda** [comment]
In the meantime, I will use this SVG as a specific placeholder for Siskin.
```xml
<svg xmlns="http://www.w3.org/2000/svg"
     viewBox="0 0 100 100">
  <text y=".9em" font-size="80">🐦‍⬛️</text>
</svg>
```

**Comment by hantu85** [comment]
I've added logo in SVG to the repository - https://github.com/tigase/siskin-im/blob/devel/logo.svg

**Comment by sjehuda** [comment]
Thank you!

Siskin has been added to the selection!

https://git.xmpp-it.net/sch/FASI/commit/373b7b1f05d3f3c3b5cd4f3a17589db25a0bca2d#diff-4d420c68bc1d32be5068812a8a23a6534c472562

**Comment by stokito** [comment]
There is also a variant with a shadow
https://tigase.org/assets/images/logos/Siskin-shadow.svg
