### ISSUE TITLE
Be able to select a MUC trough MUC overview

### ISSUE THREAD

**Issue by jnaeff** [tigase/siskin-im#28]
**Is your feature request related to a problem? Please describe.**
On BeagleIM it is possible to get an overview of the available MUC chat groups. It would be really nice if the same functionality also became available in SiskimIM. In the current version, it is kind of hard to add a MUC. You need to remember the name and then type it manually. 

**Describe the solution you'd like**
If you get an overview of the available MUC chat like in BeagleIM it is much easier to add a MUC chat.

**Comment by hantu85** [comment]
This task is completed and you can browse chats with new version which is being alfatested.
