### ISSUE TITLE
Support accepting calls from Conversations, i.e. Jingle Message Initiation

### ISSUE THREAD

**Issue by stevenroose** [tigase/siskin-im#34]
Summary: https://twitter.com/iNPUTmice/status/1252531142831616003

**Comment by hantu85** [comment]
That is on our roadmap, but Conversations will support our way of initiating a call as well.

The next build of SiskinIM in TestFlight (and next beta build of BeagleIM) may support that

**Comment by ana-jd** [comment]
I think Conversations just did support Siskin way of initiating the call. so to have a call between Siskin and conversations you need that siskin initiates the call for now and not the other way around.

Do you have any news regarding this subject please ?

**Comment by hantu85** [comment]
That is solved in beta builds and will be fixed in the next version

**Comment by yannjor** [comment]
Has this been fixed? I am still having issues, calls from Siskin to Conversations work but not the other way around.

I am using Conversations from F-Droid which seems to be a few releases behind the Play store version. Perhaps this is the reason?

**Comment by licaon-kter** [comment]
Nope, the reason is that Apple kills the app.

AFAIK, the hope is that the Tigase team ( ahem @hantu85 @woj-tek any day now, right?) standardize the XEPs used in their push server _(or whatever)_ to actually send pushes for calls too, so that a push wakes up the app and the app can see the actual call.

ref: https://xeps.tigase.net/

**Comment by yannjor** [comment]
@licaon-kter  Do you happen to know of any iOS app that supports this right now?

**Comment by licaon-kter** [comment]
@yannjor Siskin with accounts on sure.im or tigase.im or jabber.today or xmpp.cloud :)

**Comment by neilzone** [comment]
Hello! It looks like this is still open? 

I'm experimenting with Siskin IM on iOS, Conversations on Android, and Dino on Linux, using a self-hosted ejabberd server, and I can originate calls from Siskin, and they work fine, but I cannot originate calls on Android/Linux to Siskin.

Based on this thread, am I right in thinking that this isn't something I can readily solve?

**Comment by hantu85** [comment]
It depends on the server which you are using to host your account. AFAIR, push notifications for calls should work with Tigase XMPP Server and Prosody.

**Comment by neilzone** [comment]
Thanks! It's a self-hosted ejabberd server (sadly, for this).

I appreciate your (instant!) response.
