### ISSUE TITLE
Difficult to see profile picture placeholder with dark theme

### ISSUE THREAD

**Issue by ldvc** [tigase/siskin-im#38]
**Describe the bug**
Context: I've just created an account. After successful login, I would like to customize my account by setting a profile picture (avatar). While using a dark theme on iOS, the location for the photo is almost impossible to detect (cf. screenshot below).

**To Reproduce**
1. Go to 'Settings'
2. Click on the account in the *ACCOUNTS* section
3. Click on the account name
4. Try to find where to choose your profile picture

**Expected behavior**
Make some default avatar which would help user to find how to change it?

**Screenshots**
<img width="1024" alt="siskin_edit_profile_no_placeholder_picture" src="https://user-images.githubusercontent.com/5823358/81611760-ed810d00-93db-11ea-8bbf-df1bf21e4b63.png">
**Smartphone (please complete the following information):**
 - Device: iPad
 - OS: 13.4.1
 - Browser safari
 - Version the one shipped with 13.4.1
 - Siskin 6.0 from TestFlight

**Comment by hantu85** [comment]
There is a default profile picture set but it is not visible. Currently, we are reworking the whole profile editing UI so that will be improved. I'm closing as new UI (not released for testing) will not have that issue.

**Comment by ldvc** [comment]
Thanks!
