### ISSUE TITLE
Unable to delete accounts

### ISSUE THREAD

**Issue by billroland** [tigase/siskin-im#40]
**Describe the bug**
I have added several XMPP accounts and wish to delete some of them.  If there is an option to delete the accounts, I cannot find it.  Moreover, account information persists even after uninstalling and reinstalling the app.

**To Reproduce**
1. Go to Accounts
2. Attempt to find any way to delete one

**Expected behavior**
You'd expect to have an option to delete an account.

**Smartphone (please complete the following information):**
 - Device: iPhone 8
 - OS: iOS 13.4.1

**Comment by hantu85** [comment]
Just swipe left on the accounts list item.
