### ISSUE TITLE
Beta TestFlight for XEP215 STUN/TURN

### ISSUE THREAD

**Issue by Sablya122** [tigase/siskin-im#42]
I need XEP215 calls that are available in beta, please give access to beta.

**Comment by hantu85** [comment]
There is no support for XEP-0215, even in beta. There is only support for Jingle VOIP calls and Jingle Message Initiation.

**Comment by hantu85** [comment]
Suport for XEP-0215 is now in the latest version of SiskinIM released to AppStore.
