### ISSUE TITLE
Video rendering issue in video call

### ISSUE THREAD

**Issue by Mahavir2405** [tigase/siskin-im#46]
**Describe the bug**
I’m facing an issue in video call rendering using Siskin-IM. I followed below steps:

**To Reproduce**
STEP: 1
1. I downloaded the latest source code from https://github.com/tigase/siskin-im (master branch). I resolved issues related to missing libraries. I added https://github.com/tigase/tigase-swift-omemo (master branch) through “Swift package” and OpenSSL. After resolving missing library issues I found errors in some classes like:

a ) AccountSettingsViewController -> “Expression type '()' is ambiguous without more context” (updateView  /archivingSwitchChangedValue functions)
b ) CustomChatManager -> “Value of type 'ChatStore' has no member 'getChat’”
c ) DBChatStoreWrapper -> “Type 'DBChatStoreWrapper' does not conform to protocol 'ChatStore’”
d ) DBRoomsManager -> “Property 'store' with type 'DBChatStore' cannot override a property with type 'RoomStore'”  

And many more errors and that source code didn’t work for me.

STEP: 2
1. I downloaded source code https://github.com/tigase/siskin-im/tree/mix (mix branch). I resolved issues related to missing libraries. I added https://github.com/tigase/tigase-swift-omemo (master branch) through “Swift package” and OpenSSL. I can generate build using this source code and I can install this app on my iPhone. Now I’m facing a video rendering issue while making a video call. Audio is working fine but I can't see anything from the other side. I need your help and guidance to resolve this issue. Please correct me if I’m missing anything or doing anything wrong.

**Smartphone (please complete the following information):**
 - Device: iPhone 8
 - OS: iOS 13.1.2

**Screenshots**
![IMG_0451](https://user-images.githubusercontent.com/34741812/87801978-24592080-c86e-11ea-8d8f-a8dcaf3ea0f8.PNG)

**Expected behaviour**
 - when I make a video call I could see video from the other side and vice versa.

**Comment by hantu85** [comment]
I've seen an issue like that when remote client was not sending any video stream. Similar issue also appeared when another client used bundle in WebRTC but did not advertised that. Another known cause was when some extension was used while it was not negotiated. 

Basically, there is no simple answer to the question what was wrong. 
What was the client on the other end of the video call?

Another thing to explore/check would be analysis of Jingle packets and their payload.

**Comment by Mahavir2405** [comment]
Thanks for your prompt reply. What do you suggest for STEP: 1 which is a master branch source code. It is showing errors as described in my question

**Comment by hantu85** [comment]
Master branch contains source code for the last stable version and it uses older version of TigaseSwift (stable branch if I remember correctly). Soon, `mix` branch will become `master` and that issue will be solved.
