### ISSUE TITLE
'Create' button does not dismiss group chat creation dialog

### ISSUE THREAD

**Issue by mwild1** [tigase/siskin-im#47]
**Describe the bug**
On the final stage of creating a private group chat, the 'Create' button creates the chat but does not dismiss the dialog.

The behaviour was experienced while connected to Prosody trunk, other servers have not been tested.

**To Reproduce**
1. From the chats screen tap '+'
2. Tap 'Create private group chat'
3. Enter required fields and tap 'Next'
4. Enter nickname and tap 'Create'

**Expected behavior**
The dialog should close and I should be taken back to the chats screen or to the new chat.

Instead it remains open, and tapping 'Create' again creates another group chat with the same name. The dialog can be dismissed through going back and then tapping 'Cancel', then the created chat(s) are visible.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone SE
 - OS: iOS 13.5.1

**Comment by hantu85** [comment]
This issue is now fixed and will be released in the next version (or in the next build distributed via TestFlight).
