### ISSUE TITLE
Push notification not working 

### ISSUE THREAD

**Issue by faraan** [tigase/siskin-im#51]
**Describe the bug**
Hi , Push notifications are not working , 
Is apns certificate needed to configure ? How to configure to setup apns in server

**Comment by woj-tek** [comment]
Could you give more information?

* which SiskinIM version do you use?
* have you enabled push notifications in settings and account?
* on which server do you have account?
    * (if you are self-hosting - which software do you use)

**Comment by faraan** [comment]
yes sure , 

- I am using version 5.8.1
- yes have enabled 
- self hosted ejabberd server 

thanks

**Comment by woj-tek** [comment]
Can your server connect with `push.tigase.im`? Can you see in the logs that notifications are generated and send to `push.tigase.im`?

**Comment by faraan** [comment]
Ok I will check

**Comment by faraan** [comment]
I just checked with appstore version ,its working but when I install app from code through xcode , it doesn't work

**Comment by hantu85** [comment]
We are glad that PUSH notifications are working for you using Siskin from the AppStore.

As for application installed from the XCode will not work with PUSH component provided by us (`push.tigase.im` or `push.tigase.im`). Those components need to use certificate for authentication to APNS which are issues for specific compilation of the application (same signing entity) and will not be able to send PUSH notifications to your version of the application as it has different signer certificate (your developer certificate) and those PUSH notifications will be rejected by APNS.

**Comment by faraan** [comment]
@hantu85 Thanks for the details ,
just one question , how to configure push notification on our own server , do I need to use FCM or any other service ?

**Comment by hantu85** [comment]
If you are using SiskinIM from the AppStore then you just need XMPP server with Push Notifications support enabled (you need to check documentation of a particular server) and S2S (server-to-server) connectivity to `push.tigase.im` needs to work correctly.

**Comment by faraan** [comment]
thanks , but i am trying to configure push notification into my own server , It will be very helpful , if you can share some guidelines to configure push

**Comment by woj-tek** [comment]
As explained in [XEP-0357: Push Notifications](https://xmpp.org/extensions/xep-0357.html) specification, there are a couple of parts when it comes to "push notifications": client application, client server and agent server. First to items go hand in hand (so Siskin distributed by Tigase will user Tigase client server). At the same time you have complete freedom regarding agent server (your own server) and it's configuration.

If you are still interested in the "client" part (application and server) then tigase offers dedicated [Tigase Push Component](https://docs.tigase.net/tigase-push/1.1.0/Tigase_Push_Notifications_Guide/html/) as a [licensed offering](https://tigase.net/pricing-xmpp) and you should contact us directly regarding it's usage: https://tigase.net/technical-support
