### ISSUE TITLE
Group member not visible in group when offline 

### ISSUE THREAD

**Issue by faraan** [tigase/siskin-im#54]
**Describe the bug**
All group members are not visible in group member list , when a particular user is offline 

**To Reproduce**
1. Create a group, 
2. add some user to group and all invited users are joined 
3. Suppose total group member list is 5 
4. when a user goes offline , he disappears from group members list 

Is there any setting needs to enable ?

**Comment by woj-tek** [comment]
Which server (software or service domain) do you use?

**Comment by faraan** [comment]
Thanks for quick reply ,

I checked with sure.im and tigase.im .
I also checked with local host ejabberd server

**Comment by faraan** [comment]
This occurs in public group chat , in private group chat all members are displayed

**Comment by hantu85** [comment]
If you are referring to the list of participants of the MUC room visible in the UI of SiskinIM, then there is nothing to change there as this list presents a list of active and joined occupants. By default MUC kicks users out of the room when they are disconnected and after reconnection their clients joins the room again.

**Comment by woj-tek** [comment]
@faraan it's worth mentioning that we in Tigase are dedicated to bring newer, state of the art form of group conversations powered by MIX to the XMPP ecosystem: https://tigase.net/tigase-im-mix/. 

With MIX channels you won't have an issue with member disappearing from a list of room members depending on it's connection status (and it will solve more issues). Server wise it's already available on xmpp.cloud/tigase.im/sure.im and in our clients it's in current test versions, which should be released soon. For legacy clients without MIX support it would be still possible to connect to MIX channels using translation layer (MIX-MUC, implemented in Tigase XMPP Server already)

I do encourage you to try them out :-)

**Comment by faraan** [comment]
@hantu85  thanks , yes I am referring to the list of participants of the MUC room. 

@woj-tek Ok thanks , Sure I will check , so mix will work with any custom server (any specific configuration needed) of only with xmpp.cloud/tigase.im/sure.im .

**Comment by faraan** [comment]
@woj-tek Does MIX branch code have all MIX-MUC features ?
I will check the MIX branch code also

**Comment by hantu85** [comment]
MIX branches are already merged to `master` branch, so all MIX features are already part of a TestFlight build which soon should be released as official release.

However, MIX is quite a new specification and server which will need to host your channels (equivalent of a MUC room) needs to support this new sepecification.

**Comment by woj-tek** [comment]
@faraan regarding support - MIX is relatively new spec (only 4-ish years) but it's adoption was slow. You can test it on xmpp.cloud/tigase.im/sure.im and if you want you can deploy Tigase XMPP server (https://github.com/tigase/tigase-server/) to your own instance (maybe even with docker for convenience: https://github.com/tigase/tigase-xmpp-server-docker)

**Comment by faraan** [comment]
@hantu85 Ok thanks , I will check master branch .

@woj-tek thanks , sure I will check tigase server , so Is tigase server is available free to use in our own instance ?

**Comment by woj-tek** [comment]
> @woj-tek thanks , sure I will check tigase server , so Is tigase server available free to use in our own instance ?

Yes, it is! :-)

It's open source and you can install it freely on your deployment (some advanced features like advanced clustering or auditlog may require license, please check https://tigase.net/pricing-xmpp for details)
