### ISSUE TITLE
Gravitational forces squeezing (i) in MUC title

### ISSUE THREAD

**Issue by ingoj** [tigase/siskin-im#55]
As @woj-tek put it: gravitationl forces causing the (i) in MUC title to get squeezed quite heavily: 
![image](https://user-images.githubusercontent.com/18173881/92141551-e2cb0780-ee12-11ea-8b87-70bd3381b9d8.jpg)

So, please add a super-heavy Higgs-Bosom or other elementary super-mass to stretch the (i) back to normal shape. 
;-) 

PS: this is in stable release as well as in testflight.

**Comment by hantu85** [comment]
This is not it TestFlight, at least it shouldn't be in todays build.

**Comment by ingoj** [comment]
Well, it is from todays TestFlight: 
![Foto 20-09-03 19-02-05 2256](https://user-images.githubusercontent.com/18173881/92145416-81a63280-ee18-11ea-8c67-32f82a25a51a.png)
![Foto 20-09-03 19-02-21 2257](https://user-images.githubusercontent.com/18173881/92145423-84a12300-ee18-11ea-95bd-83fe910006e5.png)
![Foto 20-09-03 19-02-32 2258](https://user-images.githubusercontent.com/18173881/92145430-87037d00-ee18-11ea-8c12-310cbe0b3a7e.png)

**Comment by hantu85** [comment]
Let me guess, phone with very small screen? Could you state the phone model? or at least screen size?

**Comment by hantu85** [comment]
Either way, I've changed behaviour in the layout so according to Apple it should scale properly. Oh well, next thing which is not working as it should.

**Comment by ingoj** [comment]
> Let me guess, phone with very small screen? Could you state the phone model? or at least screen size?

It's a iPhone SE (not the new SE2). :)
