### ISSUE TITLE
Cannot receive phone calls in background or when the screen turns off

### ISSUE THREAD

**Issue by uypoko** [tigase/siskin-im#59]
**I have a problem with…**
I'm building an app using Siskin IM as an example. I got a problem where phone calls cannot be received if the screen turns off or it's in the background.
When opening the app again, the phone call screen displays

I have adopted CallKit, PushKit as in Siskin.
JingleModule.JingleMessageInitiationEvent is supposed to be called in the background but it's only called when the app opens.

Can you help me? I'd really appreciate it.

**Details (please complete the following information):**
 - Tigase version: newest
 - Xcode 12.0
 - Operating system/distribution/version: macOS 10.15.7

**Comment by hantu85** [comment]
When in background, your app is most likely stopped or killed and the only way to receive a call is to use PushKit and its notifications. To do that you need to have a server-side part which will send PushKit notifications when incoming call is detected.

Please check if you have correct background modes enabled in the application entitlements as without that it may not be allowed to run in the background.

**Comment by uypoko** [comment]
I have adopted PushKit and successfully got the push token. However, the didReceiveIncomingPushWith function is not getting called.

I also enabled background mode for VoIP.
When using Siskin with an account from our domain, the app works perfectly which probably means our server is correctly configured. I wonder if a dedicated server-side part is required to work with PushKit.

**Comment by hantu85** [comment]
Siskin uses our backend server-side component to construct notification and pass it to PushKit services and it will only work for our application (filtering is done by PushKit servers based on authorization). And we have authorization credentials only for SiskinIM so it works only for SiskinIM. You need custom backend for your app to handle PushKit and Push Notifications as well.
