### ISSUE TITLE
A warning notification should be displayed when the user swipes the app away

### ISSUE THREAD

**Issue by marmistrz** [tigase/siskin-im#6]
As discussed in the MUC, currently Siskin won't receive any notifications if the application is swiped away. it would be a good idea to display a warning notification when a user does it, until the APNS-based push is implemented in Siskin.

See also how Whatsapp shows a similar notification when the app is swiped away. https://www.thesun.co.uk/wp-content/uploads/2017/11/img_26781.jpg?w=620

**Comment by hantu85** [comment]
New push notifications are now part of the new version of Siskin. I'm closing this issue.
