### ISSUE TITLE
Can't find screen recording (video) 

### ISSUE THREAD

**Issue by mdosch** [tigase/siskin-im#61]
I recorded a video of the screen following [this guide](https://support.apple.com/en-us/HT207935) and wanted to share it via siskin. Using the paper clip symbol I could not navigate to any folder containing that video. Using the image symbol I only had access to pictures but couldn't find the video.

**To Reproduce**
1. Record the screen to a video
2. Open Sisking
3. Open a chat
4. Try to send the video via the paper clip symbol
5. Try to send the video via the image symbol

**Expected behavior**
One of these methods (paper clip/image) should be able to choose and send the video.

**Screenshots**
![image](https://user-images.githubusercontent.com/5103003/95675082-c742e180-0bb4-11eb-8a6c-c09882c5fba9.jpg)

![image_decrypted](https://user-images.githubusercontent.com/5103003/95675084-c90ca500-0bb4-11eb-8076-76170a4dc7fb.jpg)

![image_decrypted_decrypted](https://user-images.githubusercontent.com/5103003/95675085-cad66880-0bb4-11eb-95e4-d9d8e21f004d.jpg)

**Details (please complete the following information):**
 - Siskin Version: 6.0
 - iOS version 12.4.8
 - iPhone model iPhone6

**Comment by hantu85** [comment]
It is enhancement (not a bug) as we never offered a way to send a movie from the photo album. We supported only sending images and files.

This feature will be added in the next release and it will be possible to select videos from the photo album after tapping on the image symbol.

**Comment by mdosch** [comment]
Am 13. Oktober 2020 12:35:06 UTC schrieb "Andrzej Wójcik" <notifications@github.com>:
>It is enhancement (not a bug) as we never offered a way to send a movie from the photo album. We supported only sending images and files.
>
>This feature will be added in the next release and it will be possible to select videos from the photo album after tapping on the image symbol.
>

I would have happily sent it as a file, but I didn't find the video file in the send file dialogue either.

**Comment by hantu85** [comment]
You could do that but (due to how iOS behaves) you would need to enter photos app, select a movie, tap "share" icon and then select "Save in Files" and save the file. Without that your movie is inaccessible as a file for any other app.

**Comment by hantu85** [comment]
In the next beta build of Siskin 6.1 (beta 1), this should be available and working.
