### ISSUE TITLE
Voip call not connecting for USA regions

### ISSUE THREAD

**Issue by faraan** [tigase/siskin-im#63]
**Describe the bug**
I am using the latest version of app , when trying voip call in India its working but when tried calling to USA region it stucks to connecting and call never gets connected .

I tried with different servers , same issue in all 

Thanks

**Comment by hantu85** [comment]
This is not a bug.

SiskinIM uses WebRTC for peer to peer connections and if possible uses STUN servers which not in all cases are enough to establish peer to peer connection.

To make it more reliable SiskinIM (beta version) uses TURN servers provided by the XMPP servers to which it is connected.

**Comment by faraan** [comment]
Ok thanks ,
How can I check the beta version of app . or which branch to check for it . i will try testing with it 

When both devices are connected to same network , call is successfully connected but with different network connection , it couldn't connect .

**Comment by hantu85** [comment]
You should try latest stable version 6.1 as it has support for TURN.
