### ISSUE TITLE
Send Voice Messages

### ISSUE THREAD

**Issue by mwlczk** [tigase/siskin-im#66]
**Is your feature request related to a problem? Please describe.**
I would like to be able send voice messages out of the siskin app. 

**Describe the solution you'd like**
there should be a button I can tap to start record the voice / sound (only) message. Then when I tap again or realese that button the recording should finish. Then I can choose to either send the recording or abort and not to send.

**Describe alternatives you've considered**
record voice message in voice-memo-app. share from voice-memo-app to siskin.

**Additional context**
sharing from other app does send the message unencrypted!

**Comment by hantu85** [comment]
> sharing from other app does send the message unencrypted!

Yes, it was mentioned and unfortunately due to how iOS works it is impossible to be able to share from the other apps and have messages encrypted.

**Comment by hashilsemin** [comment]
anyone tried this?

**Comment by MuhammedAnasm4444** [comment]
Have anyone tried Snikket ???

**Comment by licaon-kter** [comment]
There's a voice feature just merged, maybe soon in beta.

**Comment by hantu85** [comment]
Build with support for voice messages is now available in TestFlight.
