### ISSUE TITLE
Start Audio call fails

### ISSUE THREAD

**Issue by mwlczk** [tigase/siskin-im#77]
**Describe the bug**
When initiating an audio call - this fails. 
Receiving one works fine. Initiating a video call works fine.

**To Reproduce**
1. Go to 'Chat-Window of a user who is capable of A/V calls'
2. Click on 'phone handset' to initiate an audio call
3. See error: call failed

**Expected behavior**
The call should be established the same way as an incoming audio-call or video-calls (they work both ways) in general.

**Screenshots**
i might add later if needed.

**Details (please complete the following information):**
 - Siskin Version: [e.g. 6.2(1)]
 - iOS 12.4.9
 - iPhone 5s

**Additional context**

**Comment by hantu85** [comment]
I've just checked with not yet released 6.2 beta 4 and it looks like audio calls are working fine now.
