### ISSUE TITLE
black screen when make a video call with  android apps 

### ISSUE THREAD

**Issue by muisawe** [tigase/siskin-im#79]
**Describe the bug**
  When initiating  video call  with android client such as Conversation  android will not receive any video stream but siskin will receive conversation video stream 
**To Reproduce**
1. Download master branch 
2. run the app 
3. go to one to one chat 
4. chose video call 
5. accept the call from android side 

**Expected behavior**
video call working as expected in both android and ios  

**Screenshots**

**Details (please complete the following information):**
 - Siskin Version: master version 
 -   master 
 - Xcode version: 12.3
 - iOS version 12.3 , 12,2
 - iPhone model Iphone XR 

**Additional context**
you will find the same issue on the app store

**Comment by licaon-kter** [comment]
@muisawe could you join the support group: xmpp:tigase@muc.tigase.org?join and test some webrtc updates for Conversations?

**Comment by hantu85** [comment]
This issue is already resolved in a beta build and will be fully resolved in the version from AppStore in the next release.

**Comment by muisawe** [comment]
so how would i access to the last source code update ?

**Comment by hantu85** [comment]
Source code is already in the repository. New version will be released once it is accepted as stable.

**Comment by muisawe** [comment]
which branch ?, i use the master one

**Comment by hantu85** [comment]
it already has this fix

**Comment by hantu85** [comment]
Please keep in mind that some changes are also in related libraries which SiskinIM uses

**Comment by muisawe** [comment]
I downloaded the source 3 days ago, and test it with conversation the last night.

**Comment by hantu85** [comment]
Have you updated Swift packages?

I do have a confirmation that the fix (which is currently in the repository) is working in our beta builds, so this issue is fixed.

**Comment by muisawe** [comment]
It works on some devices, but not all

**Comment by hantu85** [comment]
If something does not work on your own build then you need to fix it. As I've said, our latest fix is confirmed to work and build available via TestFlight does not have this issue any more AFAIK. If you will find an issue in the build from TestFlight, then we will look into it.

**Comment by muisawe** [comment]
how would i access to TestFlight version ?

**Comment by muisawe** [comment]
Hello again, @hantu85 
i just get access to beta version of siskin im (6.2) beta 5 , the issue is steal appears with some android devices with conversation client.

**Comment by licaon-kter** [comment]
@muisawe see my post above pls

**Comment by muisawe** [comment]
opps im sorry , i didn't notice it , how could i join your group?

**Comment by licaon-kter** [comment]
Join that group with your client.

@hantu85 maybe you can explain the workflow for Siskin ? :)
