### ISSUE TITLE
Siskin IM how to enable background message reception and notification

### ISSUE THREAD

**Issue by danjde** [tigase/siskin-im#81]
Hi Devs!
Using Siskin IM Ver 6.1 on Iphone 7 Ver 13.3.1,
the chat messages are downloaded (and notified) only if you access directly to the application.
I've read the Siskin IM (Tigase?) manual (https://docs.tigase.net/tigase-ios/master-snapshot/Tigase_Swift_Guide/html/#acctSettings) but i can't figure out what option i should enable.

Could you give me any tips?

Many thanks!

Davide

**Comment by licaon-kter** [comment]
Better join the support group:  `xmpp:tigase@muc.tigase.org?join`

**Comment by woj-tek** [comment]
@danjde have you enabled push notifications in Siskin? Does your server support push notifications?

**Comment by danjde** [comment]
> Does your server support push notifications?

Sure! -> Prosody 11.x



> @danjde have you enabled push notifications in Siskin?

The matter is a bit strange. I've not the phone, it belongs to a friend of mine, and she assures me that this menu item is not present.
But, if you say there must be, I'll do this verification!


Thanks @woj-tek !

**Comment by woj-tek** [comment]
The item should be present if Siskin detects that the server supports push notifications. Can you enable push on Android devices (maybe share server address so it could be checked)?

**Comment by danjde** [comment]
> The item should be present if Siskin detects that the server supports push notifications. Can you enable push on Android devices (maybe share server address so it could be checked)?

The server address: server.3x1t.org
Then, i didn't know of the need to enable IOS push notification _server side_ and now I've enabled it.

I'll do some client side checks...

Thanks!

**Comment by woj-tek** [comment]
You shouldn't enable "ios push notifications" on the server - I only asked about android as another operating system that may require push and (hopefuly) you could use to see if push itself works.

One important bit is that you make sure that your server can establish s2s connection to `push.tigase.im` (which in fact handles Apple pushes)

**Comment by danjde** [comment]
> You shouldn't enable "ios push notifications" on the server - I only asked about android as another operating system that may require push and (hopefuly) you could use to see if push itself works.
> 

This is a bit complicated, among our users none uses XMPP client from Google Play, and only those have the push function

> One important bit is that you make sure that your server can establish s2s connection to `push.tigase.im` (which in fact handles Apple pushes)

Testing from Prosody console:

c2s:show("push.tigase.im")
| 3x1t.org
| OK: Total: 0 clients 

My curiosity: why is the "push notifications" functionality found only in the versions of the same app downloaded from Google Store or Apple Store and not on apps downloaded from F-Droid, etc?

Thanks again!

**Comment by licaon-kter** [comment]
@danjde push libs are not open-source

**Comment by danjde** [comment]
> @danjde push libs are not open-source

Ah, as I supposed!

Thanks!

**Comment by danjde** [comment]
> @danjde push libs are not open-source

..but the developers known what these libs contains (other what is stated)?
The code while being proprietary is transparent? Or not?...

Thanks

**Comment by licaon-kter** [comment]
How would they know when it's closed source. They want the push thing.

On Apple they need it else the app is dead.

**Comment by danjde** [comment]
> How would they know when it's closed source? [..]
Thanks 'kter for your explanation, it's very useful for me!
If I can still take advantage of your courtesy, I would to know why "push" technology does not exist in the OpenSource form.
Play Store and Apple Store are very opaque, how can the end user understand if an Open Source software contains proprietary software? Reading pages and pages of licenses? Maybe not even.
These seem to me like real Trojan horses, also allowed by the institutions (thanks to their inaction)!


Thanks!

**Comment by hantu85** [comment]
Technology does not exist because the only push services allowed to run without any restrictions on mobile devices are services provided by the operating system (or hardware manufacturer as part of a custom OS), so there is no way you could use open-source push services.

On the other hand, do the operating system manufacturer need a trojan horse-like push notification service to get information about you if he just can access all your files stored on a device or catch local notifications displayed by the system as well?

**Comment by hantu85** [comment]
> Play Store and Apple Store are very opaque, how can the end user understand if an Open Source software contains proprietary software? Reading pages and pages of licenses? Maybe not even.

Open Source software does not contain proprietary software, it is just liked with them (actually operating system provides those libraries which are proprietary, so you already accepted they license by using this operating system).

On the Apple Store any app using push notifications uses proprietary software. Even an app not using push notifications does that as it uses iOS API and frameworks which are proprietary. I would say that the same goes (at least partially) for Play Store (or rather any app using Play Store Services, or Google Service, I do not recall the name of those services).

**Comment by danjde** [comment]
> [..]if he just can access all your files stored on a device or catch local notifications displayed by the system as well?

Not at all, I'm using for example LineageOS, without Gapps, and here a Google/IOS Trojan Horse could be very useful..

> On the Apple Store any app using push notifications uses proprietary software.

Sure, but is not clear for me if the OpenSource apps must include a portion of proprietary software in order to communicate with the proprietary APIs...

Thanks hantu85, very interesting!

**Comment by licaon-kter** [comment]
Actually all Apple Store apps come bundled with some DRM anyway.

@danjde I've mentioned the support groups exactly to discuss these, already offtopic here, matters :)

**Comment by danjde** [comment]
> Actually all Apple Store apps come bundled with some DRM anyway.
> 

Right!

> @danjde I've mentioned the support groups exactly to discuss these, already offtopic here, matters :)

Sure, excuse me all of you!
And thanks to all for the kind answers!

**Comment by danjde** [comment]
Excuse me If I return back here, but I cannot send messages into Tigase Support Channel, where I can read the messages but I cannot write into. @licaon-kter could you help me? My Jabber address is: cosmogonia AT 3x1t DOT org.

In any case.thanks!

**Comment by licaon-kter** [comment]
@danjde try to use only one client () any error messages?

**Comment by earboxer** [comment]
So I have a prosody server and I have iOS users running siskin.im. How can I make sure that my server supports the push notification functionality that siskin.im uses?

(`prosodyctl list` says I have `mod_cloud_notify`, `mod_cloud_notify_encrypted`, 
`mod_cloud_notify_extensions`, `mod_cloud_notify_filters`, `mod_cloud_notify_priority_tag`, so I think I should be good, but my iOS users say they miss notifications).

(It would be really cool to have a site like https://compliance.conversations.im that we could use to test our servers for this functionality)

Could we have screenshots from this App showing our users how to enable push notifications?
