### ISSUE TITLE
There is no XCFramework found

### ISSUE THREAD

**Issue by medic345** [tigase/siskin-im#85]
When I try to run the project the project fails and I get two issues. "There is no XCFramework found at ...../frameworks/webRTC.xcframework

additionally

"There is no XCFramework found at ...... /frameworks/OpenSSL.xcframwork

When I go to my master tree and select Build Phases > embed frameworks Those frameworks are listed there.

Sorry if this is a really amature question.

**Comment by hantu85** [comment]
Just run `update-frameworks.sh` from the command line and it will fetch, test checksums and unpack those frameworks.

**Comment by medic345** [comment]
whoops! Missed that.. Thank you!
