### ISSUE TITLE
Previously Destroyed MUC Re-Appears in UI and Freezes Siskin

### ISSUE THREAD

**Issue by Ged296123** [tigase/siskin-im#98]
Describe the bug
Occassionally (not always) previously destroyed MUC reappears in UI. In this case, app tries to join destroyed MUC and freezes.

To Reproduce

Start app.
On occasion (not always, unfortunately cannot re-produce this state), MUC that was destroyed in the past re-appears in UI.
If above state occurs, Siskin tries to join destroyed MUC and freezes or if I try to delete MUC with swipe gesture, app freezes. If above state does not occur, app runs normally as before.
Have to reset app to be able to use it again.
Expected behavior
A destroyed MUC should not be seen in UI, app should not freeze when this happens.

Screenshots
N/A

Details (please complete the following information):

Siskin Version: 6.2
iOS version: 14.4
iPhone model: iPhoneX
Additional context

**Comment by licaon-kter** [comment]
Did you enable Bookmark Sync is Settings?

**Comment by Ged296123** [comment]
> Did you enable Bookmark Sync is Settings?

Yes, it's enabled.

**Comment by mimi89999** [comment]
Maybe related to https://github.com/tigase/siskin-im/issues/94

**Comment by Ged296123** [comment]
> Maybe related to #94

I think so too... only in this instance, the user was not only removed, but the MUC was destroyed.

**Comment by mimi89999** [comment]
@Ged296123 Could you please test in the latest version in TestFlight?
